
package view;

import java.awt.Color;

import javax.swing.table.DefaultTableCellRenderer;

public class HopDongView extends javax.swing.JPanel {

    /**
     * Creates new form HopDongView
     */
    public HopDongView() {
        initComponents();
        setBounds(0,0,1287,731);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    public void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bangDV = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        Bang = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        bangMA = new javax.swing.JTable();
        CCHD = new javax.swing.JButton();
        timB = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel5.setText("Hợp đồng");
        add(jLabel5);
        jLabel5.setBounds(20, 10, 120, 30);

        bangDV.setBackground(new java.awt.Color(238, 237, 181));
        bangDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        bangDV.setGridColor(new java.awt.Color(153, 105, 211));
        bangDV.setSelectionBackground(new java.awt.Color(238, 238, 181));
        jScrollPane2.setViewportView(bangDV);

        add(jScrollPane2);
        jScrollPane2.setBounds(980, 430, 280, 260);

        Bang.setBackground(new java.awt.Color(238, 237, 181));
        Bang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        Bang.setGridColor(new java.awt.Color(153, 105, 211));
        Bang.setSelectionBackground(new java.awt.Color(238, 238, 181));
        jScrollPane4.setViewportView(Bang);

        add(jScrollPane4);
        jScrollPane4.setBounds(20, 150, 930, 540);

        bangMA.setBackground(new java.awt.Color(238, 237, 181));
        bangMA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        bangMA.setGridColor(new java.awt.Color(153, 105, 211));
        bangMA.setSelectionBackground(new java.awt.Color(238, 238, 181));
        jScrollPane3.setViewportView(bangMA);

        add(jScrollPane3);
        jScrollPane3.setBounds(980, 150, 280, 260);

        CCHD.setBackground(new java.awt.Color(238, 237, 181));
        CCHD.setText("CTHD");
        //add(CCHD);
        CCHD.setBounds(1160, 110, 100, 23);

        timB.setBackground(new java.awt.Color(238, 237, 181));
        timB.setText("Tìm");
        add(timB);
        timB.setBounds(850, 70, 100, 23);

        jButton3.setBackground(new java.awt.Color(238, 237, 181));
        jButton3.setText("Thêm hợp đồng");
        add(jButton3);
        jButton3.setBounds(20, 70, 150, 23);
        add(jTextField1);
        jTextField1.setBounds(980, 70, 280, 22);
    	Bang.setGridColor(new java.awt.Color(153, 105, 211));
        Bang.setSelectionBackground(new java.awt.Color(238, 238, 181));
		Bang.setBackground(Color.white);
		DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();

		// Thiết lập màu cho thanh mô hình
		headerRenderer.setBackground(new java.awt.Color(238, 238, 181));
	//	headerRenderer.setForeground(Color.);

		// Thiết lập renderer cho mô hình của thanh
		Bang.getTableHeader().setDefaultRenderer(headerRenderer);
		
		
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    public javax.swing.JTable Bang;
    public javax.swing.JButton CCHD;
    public javax.swing.JTable bangDV;
    public javax.swing.JTable bangMA;
    public javax.swing.JButton jButton3;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JButton timB;
    // End of variables declaration                   
}
