
package view;

import java.awt.Color;

import javax.swing.table.DefaultTableCellRenderer;

public class NhanVienView extends javax.swing.JPanel {

    /**
     * Creates new form NhanVienView
     */
    public NhanVienView() {
        initComponents();
        setBounds(0,0,1287,731);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    public void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        maL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Bang = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tenTF = new javax.swing.JTextField();
        chucvuTF = new javax.swing.JTextField();
        cccdTF = new javax.swing.JTextField();
        timTF = new javax.swing.JTextField();
        suaB = new javax.swing.JButton();
        xoaB = new javax.swing.JButton();
        clearB = new javax.swing.JButton();
        TimB = new javax.swing.JButton();
        maJL = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userTF = new javax.swing.JTextField();
        maTF = new javax.swing.JTextField();
        soTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        suaB1 = new javax.swing.JButton();
        xoaB1 = new javax.swing.JButton();
        mucTB = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        diaChiTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        suaB2 = new javax.swing.JButton();
        suaB3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        jLabel12.setText("jLabel12");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel5.setText("Nhân viên");
        add(jLabel5);
        jLabel5.setBounds(20, 10, 120, 30);

        maL.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        add(maL);
        maL.setBounds(140, 80, 120, 0);

        Bang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5",""
            }
        ));
        Bang.setDragEnabled(true);
        //Bang.setEnabled(false);
        Bang.setFocusable(false);
     
        Bang.setName(""); // NOI18N
      
        Bang.setSelectionBackground(new java.awt.Color(255, 204, 0));
        Bang.setShowVerticalLines(true);
        Bang.setUpdateSelectionOnSort(false);
        Bang.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(Bang);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 150, 890, 540);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel4.setText("Căn cước công dân ");
        add(jLabel4);
        jLabel4.setBounds(500, 100, 140, 20);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel1.setText("Tên nhân viên");
        add(jLabel1);
        jLabel1.setBounds(500, 10, 140, 20);
        add(tenTF);
        tenTF.setBounds(700, 10, 210, 22);

        chucvuTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chucvuTFActionPerformed(evt);
            }
        });
        add(chucvuTF);
        chucvuTF.setBounds(700, 40, 210, 22);
        add(cccdTF);
        cccdTF.setBounds(700, 100, 210, 22);
        add(timTF);
        timTF.setBounds(940, 10, 230, 22);

        suaB.setBackground(new java.awt.Color(238, 237, 181));
        suaB.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        suaB.setText("Thêm");
        add(suaB);
        suaB.setBounds(940, 100, 70, 22);

        xoaB.setBackground(new java.awt.Color(238, 237, 181));
        xoaB.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        xoaB.setText("Xóa");
        add(xoaB);
        xoaB.setBounds(1110, 100, 60, 22);

        clearB.setBackground(new java.awt.Color(238, 237, 181));
        clearB.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        clearB.setText("Clear");
        add(clearB);
        clearB.setBounds(1180, 100, 70, 22);

        TimB.setBackground(new java.awt.Color(238, 237, 181));
        TimB.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        TimB.setText("Tìm");
        add(TimB);
        TimB.setBounds(1180, 10, 72, 22);

        maJL.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL.setText("");
        //add(maJL);
        maJL.setBounds(130, 100, 120, 18);

        maTF.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maTF.setText("");
        add(maTF);
        maTF.setBounds(130, 100, 120, 18);
        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel8.setText("Mã nhân viên");
        add(jLabel8);
        jLabel8.setBounds(20, 100, 120, 18);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel3.setText("Địa chỉ");
        add(jLabel3);
        jLabel3.setBounds(940, 60, 90, 20);

        userTF.setText("admin");
        userTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTFActionPerformed(evt);
            }
        });
        add(userTF);
        userTF.setBounds(1050, 240, 120, 22);
        add(soTF);
        soTF.setBounds(700, 70, 210, 22);

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel6.setText("Số điện thoại");
        add(jLabel6);
        jLabel6.setBounds(500, 70, 140, 20);

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel7.setText("Mức truy cập");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        add(jLabel7);
        jLabel7.setBounds(940, 340, 140, 20);

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel9.setText("Chức vụ");
        add(jLabel9);
        jLabel9.setBounds(500, 40, 140, 20);

        suaB1.setBackground(new java.awt.Color(238, 237, 181));
        suaB1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        suaB1.setText("Thêm");
        add(suaB1);
        suaB1.setBounds(1020, 380, 70, 22);

        xoaB1.setBackground(new java.awt.Color(238, 237, 181));
        xoaB1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        xoaB1.setText("Xóa");
        add(xoaB1);
        xoaB1.setBounds(1180, 380, 72, 22);

        mucTB.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        mucTB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "mức 3", "mức 2", "mức 1" }));
        mucTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mucTBActionPerformed(evt);
            }
        });
        add(mucTB);
        mucTB.setBounds(1050, 340, 100, 21);

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel13.setText("mức 2: Truy cập với tư cách nhân viên");
        add(jLabel13);
        jLabel13.setBounds(940, 530, 260, 20);

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel14.setText("Mật khẩu");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        add(jLabel14);
        jLabel14.setBounds(940, 290, 90, 20);
        add(diaChiTF);
        diaChiTF.setBounds(1040, 60, 210, 22);

        passwordTF.setText("1");
        passwordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTFActionPerformed(evt);
            }
        });
        add(passwordTF);
        passwordTF.setBounds(1050, 290, 120, 22);

        jLabel17.setBackground(new java.awt.Color(255, 102, 0));
        jLabel17.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 153, 0));
        jLabel17.setText("Nhân viên này chưa được tạo tài khoản để đăng nhập hệ thống");
      
        jLabel17.setBounds(940, 180, 330, 20);

        suaB2.setBackground(new java.awt.Color(238, 237, 181));
        suaB2.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        suaB2.setText("Sửa");
        add(suaB2);
        suaB2.setBounds(1030, 100, 70, 22);

        suaB3.setBackground(new java.awt.Color(238, 237, 181));
        suaB3.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        suaB3.setText("Sửa");
        add(suaB3);
        suaB3.setBounds(1100, 380, 60, 22);

        jLabel18.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel18.setText("Lưu ý về mức truy cập");
        add(jLabel18);
        jLabel18.setBounds(940, 450, 320, 20);

        jLabel19.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel19.setText("Chức năng quản lý quyền đăng nhập hệ thống.");
        add(jLabel19);
        jLabel19.setBounds(940, 150, 320, 20);

        jLabel15.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel15.setText("Tài khoản");
        add(jLabel15);
        jLabel15.setBounds(940, 240, 140, 20);

        jLabel20.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel20.setText("mức 3: Hủy quyền truy cập");
        add(jLabel20);
        jLabel20.setBounds(940, 570, 240, 20);

        jLabel21.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel21.setText("mức 1 : Truy cập với tư cách quản lý");
        add(jLabel21);
        jLabel21.setBounds(940, 490, 240, 20);
    	Bang.setGridColor(new java.awt.Color(153, 105, 211));
        Bang.setSelectionBackground(new java.awt.Color(238, 238, 181));
		Bang.setBackground(Color.white);
		DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();

		// Thiết lập màu cho thanh mô hình
		headerRenderer.setBackground(new java.awt.Color(238, 238, 181));
	//	headerRenderer.setForeground(Color.);

		// Thiết lập renderer cho mô hình của thanh
		Bang.getTableHeader().setDefaultRenderer(headerRenderer);
		
		
    }// </editor-fold>                        

    public void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    public void mucTBActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    public void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    public void userTFActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    public void passwordTFActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    public void chucvuTFActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        


    // Variables declaration - do not modify                     
    public javax.swing.JTable Bang;
    public javax.swing.JButton TimB;
    public javax.swing.JTextField cccdTF;
    public javax.swing.JTextField chucvuTF;
    public javax.swing.JButton clearB;
    public javax.swing.JTextField diaChiTF;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel maJL;
    public javax.swing.JLabel maL;
    public javax.swing.JComboBox<String> mucTB;
    public javax.swing.JTextField passwordTF;
    public javax.swing.JTextField soTF;
    public javax.swing.JButton suaB;
    public javax.swing.JButton suaB1;
    public javax.swing.JButton suaB2;
    public javax.swing.JButton suaB3;
    public javax.swing.JTextField tenTF;
    public javax.swing.JTextField timTF;
    public javax.swing.JTextField userTF;
    public javax.swing.JTextField maTF;
    public javax.swing.JButton xoaB;
    public javax.swing.JButton xoaB1;
    // End of variables declaration                   
}
