package view;

import javax.swing.JFrame;

public class QuanLyLogin extends javax.swing.JPanel {
	JFrame quanLyF;
    /**
     * Creates new form QuanLyLogin
     */
    public QuanLyLogin() {
        initComponents();
        setBounds(0, 0,1287, 850);
        quanLyF = new JFrame("Dành cho quản lý");		
    	quanLyF.setSize(1287, 850);   
    	quanLyF.setLayout(null);	
        quanLyF.add(this); 
    	quanLyF.setLocationRelativeTo(null);
    	quanLyF.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    public void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        hdB = new javax.swing.JButton();
        sanhB = new javax.swing.JButton();
        khB = new javax.swing.JButton();
        maB = new javax.swing.JButton();
        nvB = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        dvB = new javax.swing.JButton();
        khungCN = new javax.swing.JPanel();

        setBackground(new java.awt.Color(238, 237, 181));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Candara", 0, 36)); // NOI18N
        jLabel2.setText("Phần mềm quản lý tiệc cưới");
        add(jLabel2);
        jLabel2.setBounds(0, 20, 430, 90);

        hdB.setBackground(new java.awt.Color(238, 237, 181));
        hdB.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        hdB.setText("Hợp đồng");
      
        add(hdB);
        hdB.setBounds(470, 50, 100, 33);

        sanhB.setBackground(new java.awt.Color(238, 237, 181));
        sanhB.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        sanhB.setText("Sảnh");
      
        add(sanhB);
        sanhB.setBounds(590, 50, 60, 33);

        khB.setBackground(new java.awt.Color(238, 237, 181));
        khB.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        khB.setText("Khách Hàng");
       
        add(khB);
        khB.setBounds(680, 50, 130, 33);

        maB.setBackground(new java.awt.Color(238, 237, 181));
        maB.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        maB.setText("Món ăn");
        maB.setBorder(null);
        maB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maBActionPerformed(evt);
            }
        });
        add(maB);
        maB.setBounds(830, 50, 80, 30);

        nvB.setBackground(new java.awt.Color(238, 237, 181));
        nvB.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        nvB.setText("Nhân viên");
        nvB.setBorder(null);
        add(nvB);
        nvB.setBounds(1050, 50, 110, 30);

        jButton2.setBackground(new java.awt.Color(238, 237, 181));
        jButton2.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jButton2.setText("Đăng xuất");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
       // add(jButton2);
        jButton2.setBounds(1200, 10, 80, 20);

        jButton1.setBackground(new java.awt.Color(238, 237, 181));
        jButton1.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jButton1.setText("Đổi mật khẩu");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
       // add(jButton1);
        jButton1.setBounds(1200, 40, 80, 17);

        dvB.setBackground(new java.awt.Color(238, 237, 181));
        dvB.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        dvB.setText("Dịch vụ");
        dvB.setBorder(null);
        add(dvB);
        dvB.setBounds(940, 50, 80, 30);
        add(khungCN);
        khungCN.setBounds(0, 120, 1287, 731);
        khungCN.setLayout(null);
    }// </editor-fold>                        

    public void maBActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    public void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    public void clickE () {
    
    
    	 khB.setBorder(null);
    	 maB.setBorder(null);
    	 nvB.setBorder(null);
    	 dvB.setBorder(null);
    	 hdB.setBorder(null);
    	 sanhB.setBorder(null);
    	 
    	 
    }
    // Variables declaration - do not modify                     
    public javax.swing.JButton dvB;
    public javax.swing.JButton hdB;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JButton khB;
    public javax.swing.JPanel khungCN;
    public javax.swing.JButton maB;
    public javax.swing.JButton nvB;
    public javax.swing.JButton sanhB;
    // End of variables declaration                   
}
