package view;

import javax.swing.JLabel;
import javax.swing.JTextField;

public class TaoHopDong extends javax.swing.JPanel {

    public JLabel maHDL;
	public JTextField maHD;
	public JTextField thanhtienHD;
	/**
     * Creates new form TaoHopDong
     */
    public TaoHopDong() {
        initComponents();
        setBounds(0,0,1287,731);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    public void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        bangDV = new javax.swing.JTable();
        dichVuB = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        maKH = new javax.swing.JLabel();
        xoaMA = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        maJL10 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        maJL11 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        maJL12 = new javax.swing.JLabel();
        maJL13 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        maJL14 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        maJL15 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        maJL16 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        maJL17 = new javax.swing.JLabel();
        maJL18 = new javax.swing.JLabel();
        thanhTienL = new javax.swing.JLabel();
        maS = new javax.swing.JLabel();
        cccd = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        themHD = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        bangMA = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tenS = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tenKH = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        maJL19 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        maJL20 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        jButton17 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        maJL21 = new javax.swing.JLabel();
        maJL22 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        maJL23 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        maJL24 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        maJL25 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        maJL26 = new javax.swing.JLabel();
        maJL27 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable11 = new javax.swing.JTable();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        maJL28 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        maJL29 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTable12 = new javax.swing.JTable();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTable13 = new javax.swing.JTable();
        jButton24 = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        maJL30 = new javax.swing.JLabel();
        maJL31 = new javax.swing.JLabel();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        maJL32 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        maJL33 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        maJL34 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        maJL35 = new javax.swing.JLabel();
        maJL36 = new javax.swing.JLabel();
        jButton29 = new javax.swing.JButton();
        jLabel61 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bang = new javax.swing.JTable();
        khachHangB = new javax.swing.JButton();
        sanhB = new javax.swing.JButton();
        monAnB = new javax.swing.JButton();
        xoaDV = new javax.swing.JButton();
        ngaydienraTF = new javax.swing.JTextField();
        sobanTF = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();

maHDL = new javax.swing.JLabel();

maHDL.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N

maHDL.setForeground(new java.awt.Color(153, 0, 51));

maHDL.setText("Mã hợp đồng");

add(maHDL);
maHDL.setBounds(270, 20, 100, 18);


maHD = new javax.swing.JTextField();



add(maHD);
maHD.setBounds(370, 20, 180, 18);

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        bangDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
               
            },
            new String [] {
            		"Mã dịch vụ","Tên dịch vụ","Giá thành","Ghi chú"
            }
        ));
        jScrollPane3.setViewportView(bangDV);

        add(jScrollPane3);
        jScrollPane3.setBounds(20, 500, 530, 110);

        dichVuB.setBackground(new java.awt.Color(0, 51, 51));
        dichVuB.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        dichVuB.setForeground(new java.awt.Color(255, 255, 255));
        dichVuB.setText("Dịch vụ");
        dichVuB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dichVuB.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        dichVuB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dichVuBActionPerformed(evt);
            }
        });
        add(dichVuB);
        dichVuB.setBounds(20, 460, 150, 30);

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel10.setText("Mã khách hàng");
        add(jLabel10);
        jLabel10.setBounds(20, 50, 120, 18);

        maKH.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        add(maKH);
        maKH.setBounds(170, 50, 120, 18);

        xoaMA.setBackground(new java.awt.Color(0, 51, 51));
        xoaMA.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        xoaMA.setForeground(new java.awt.Color(255, 255, 255));
        xoaMA.setText("xóa món ăn");
        xoaMA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        xoaMA.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        xoaMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaMAActionPerformed(evt);
            }
        });
        
        xoaMA.setBounds(450, 420, 100, 20);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "dv 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jPanel1.add(jScrollPane5);
        jScrollPane5.setBounds(640, 300, 630, 310);

        jLabel21.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel21.setText("Tên khách hàng");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(20, 80, 140, 20);

        jLabel22.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel22.setText("Căn cước công dân ");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(20, 110, 140, 20);

        jLabel23.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel23.setText("Mã khách hàng");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(20, 50, 120, 18);

        maJL10.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL10.setText("");
        jPanel1.add(maJL10);
        maJL10.setBounds(170, 110, 120, 18);

        jLabel24.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel24.setText("Mã sảnh");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(20, 190, 120, 18);

        maJL11.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL11.setText("");
        jPanel1.add(maJL11);
        maJL11.setBounds(170, 220, 120, 18);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        jPanel1.add(jScrollPane6);
        jScrollPane6.setBounds(20, 500, 570, 110);

        jButton8.setText("Thêm món");
        jPanel1.add(jButton8);
        jButton8.setBounds(450, 440, 140, 23);

        jButton9.setText("Xác nhận chỉnh sửa");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(1090, 640, 180, 23);

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTable7);

        jPanel1.add(jScrollPane7);
        jScrollPane7.setBounds(20, 300, 570, 110);

        jButton10.setText("Thay đổi khách hàng");
        jPanel1.add(jButton10);
        jButton10.setBounds(450, 110, 140, 23);

        jLabel25.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel25.setText("Tên sảnh");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(20, 220, 140, 20);

        maJL12.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL12.setText("makh");
        jPanel1.add(maJL12);
        maJL12.setBounds(170, 50, 120, 18);

        maJL13.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL13.setText("makh");
        jPanel1.add(maJL13);
        maJL13.setBounds(170, 80, 120, 18);

        jButton11.setText("Thay đổi sảnh");
        jPanel1.add(jButton11);
        jButton11.setBounds(450, 210, 140, 23);

        jButton12.setText("Xóa món");
        jPanel1.add(jButton12);
        jButton12.setBounds(250, 440, 140, 23);

        jButton13.setText("Xóa món");
        jPanel1.add(jButton13);
        jButton13.setBounds(250, 640, 140, 23);

        jButton14.setText("Thêm món");
        jPanel1.add(jButton14);
        jButton14.setBounds(450, 640, 140, 23);

        jLabel26.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel26.setText("Danh sách dịch vụ");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(20, 460, 210, 30);

        jLabel27.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel27.setText("Món ăn");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(20, 10, 120, 30);

        jLabel28.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel28.setText("Sảnh");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(20, 150, 120, 30);

        jLabel29.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel29.setText("Danh sách ");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(640, 260, 260, 30);

        maJL14.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL14.setText("mã nhân viên");
        jPanel1.add(maJL14);
        maJL14.setBounds(170, 190, 120, 18);

        jLabel30.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel30.setText("Số bàn");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(640, 20, 120, 20);

        maJL15.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL15.setText("makh");
        jPanel1.add(maJL15);
        maJL15.setBounds(780, 20, 120, 20);

        jLabel31.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel31.setText("Ngày diễn ra");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(640, 110, 140, 20);

        maJL16.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL16.setText("31");
        jPanel1.add(maJL16);
        maJL16.setBounds(830, 110, 50, 20);

        jLabel32.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel32.setText("Danh sách món ăn");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(20, 260, 210, 30);

        jLabel33.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel33.setText("Trạng thái");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(640, 210, 140, 20);

        maJL17.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL17.setText("gì đây");
        jPanel1.add(maJL17);
        maJL17.setBounds(780, 210, 120, 20);

        maJL18.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL18.setText("Ngày: ");
        jPanel1.add(maJL18);
        maJL18.setBounds(780, 110, 50, 20);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 0);

        thanhTienL.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        thanhTienL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        thanhTienL.setText("100000000");
        thanhTienL.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
       
        thanhTienL.setBounds(1120, 530, 80, 20);

        maS.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maS.setText("");
        add(maS);
        maS.setBounds(170, 190, 120, 18);

        cccd.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        cccd.setText("");
        add(cccd);
        cccd.setBounds(170, 110, 120, 18);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel5.setText("VND");
        add(jLabel5);
        jLabel5.setBounds(1210, 530, 40, 20);

        jLabel16.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel16.setText("Danh sách ");
        add(jLabel16);
        jLabel16.setBounds(570, 160, 310, 30);

        jLabel60.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel60.setText("Căn cước công dân ");
        add(jLabel60);
        jLabel60.setBounds(20, 110, 140, 20);

        themHD.setBackground(new java.awt.Color(0, 51, 51));
        themHD.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        themHD.setForeground(new java.awt.Color(255, 255, 255));
        themHD.setText("Thêm hợp đồng");
        themHD.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        themHD.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        themHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themHDActionPerformed(evt);
            }
        });
        add(themHD);
        themHD.setBounds(1120, 620, 126, 40);

        jLabel17.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel17.setText("Số bàn");
        add(jLabel17);
        jLabel17.setBounds(570, 20, 170, 18);

        bangMA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
               
            },
            new String [] {
            		"Mã món ăn","Tên món ăn","loại món ăn","Giá thành"
            }
        ));
        jScrollPane4.setViewportView(bangMA);

        add(jScrollPane4);
        jScrollPane4.setBounds(20, 300, 530, 110);

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel2.setText("Tên khách hàng");
        add(jLabel2);
        jLabel2.setBounds(20, 80, 140, 20);

        tenS.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        tenS.setText("");
        add(tenS);
        tenS.setBounds(170, 220, 120, 18);

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel13.setText("Mã sảnh");
        add(jLabel13);
        jLabel13.setBounds(20, 190, 120, 18);

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel14.setText("Tên sảnh");
        add(jLabel14);
        jLabel14.setBounds(20, 220, 140, 20);

        tenKH.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        tenKH.setText("");
        add(tenKH);
        tenKH.setBounds(170, 80, 120, 18);

        jLabel18.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel18.setText("Định dạng: dd/mm/yy");
        add(jLabel18);
        jLabel18.setBounds(900, 60, 190, 20);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(jTable8);

        jPanel2.add(jScrollPane8);
        jScrollPane8.setBounds(640, 300, 630, 310);

        jLabel34.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel34.setText("Tên khách hàng");
        jPanel2.add(jLabel34);
        jLabel34.setBounds(20, 80, 140, 20);

        jLabel35.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel35.setText("Căn cước công dân ");
        jPanel2.add(jLabel35);
        jLabel35.setBounds(20, 110, 140, 20);

        jLabel36.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel36.setText("Mã khách hàng");
        jPanel2.add(jLabel36);
        jLabel36.setBounds(20, 50, 120, 18);

        maJL19.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL19.setText("makh");
        jPanel2.add(maJL19);
        maJL19.setBounds(170, 110, 120, 18);

        jLabel37.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel37.setText("Mã sảnh");
        jPanel2.add(jLabel37);
        jLabel37.setBounds(20, 190, 120, 18);

        maJL20.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL20.setText("mã nhân viên");
        jPanel2.add(maJL20);
        maJL20.setBounds(170, 220, 120, 18);

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(jTable9);

        jPanel2.add(jScrollPane9);
        jScrollPane9.setBounds(20, 500, 570, 110);

        jButton15.setText("Thêm món");
        jPanel2.add(jButton15);
        jButton15.setBounds(450, 440, 140, 23);

        jButton16.setText("Xác nhận chỉnh sửa");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton16);
        jButton16.setBounds(1090, 640, 180, 23);

        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane10.setViewportView(jTable10);

        jPanel2.add(jScrollPane10);
        jScrollPane10.setBounds(20, 300, 570, 110);

        jButton17.setText("Thay đổi khách hàng");
        jPanel2.add(jButton17);
        jButton17.setBounds(450, 110, 140, 23);

        jLabel38.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel38.setText("Tên sảnh");
        jPanel2.add(jLabel38);
        jLabel38.setBounds(20, 220, 140, 20);

        maJL21.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL21.setText("makh");
        jPanel2.add(maJL21);
        maJL21.setBounds(170, 50, 120, 18);

        maJL22.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL22.setText("makh");
        jPanel2.add(maJL22);
        maJL22.setBounds(170, 80, 120, 18);

        jButton18.setText("Thay đổi sảnh");
        jPanel2.add(jButton18);
        jButton18.setBounds(450, 210, 140, 23);

        jButton19.setText("Xóa món");
        jPanel2.add(jButton19);
        jButton19.setBounds(250, 440, 140, 23);

        jButton20.setText("Xóa món");
        jPanel2.add(jButton20);
        jButton20.setBounds(250, 640, 140, 23);

        jButton21.setText("Thêm món");
        jPanel2.add(jButton21);
        jButton21.setBounds(450, 640, 140, 23);

        jLabel39.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel39.setText("Danh sách dịch vụ");
        jPanel2.add(jLabel39);
        jLabel39.setBounds(20, 460, 210, 30);

        jLabel40.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel40.setText("Món ăn");
        jPanel2.add(jLabel40);
        jLabel40.setBounds(20, 10, 120, 30);

        jLabel41.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel41.setText("Sảnh");
        jPanel2.add(jLabel41);
        jLabel41.setBounds(20, 150, 120, 30);

        jLabel42.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel42.setText("Danh sách ");
        jPanel2.add(jLabel42);
        jLabel42.setBounds(640, 260, 260, 30);

        maJL23.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL23.setText("mã nhân viên");
        jPanel2.add(maJL23);
        maJL23.setBounds(170, 190, 120, 18);

        jLabel43.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel43.setText("Số bàn");
        jPanel2.add(jLabel43);
        jLabel43.setBounds(640, 20, 120, 20);

        maJL24.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL24.setText("makh");
        jPanel2.add(maJL24);
        maJL24.setBounds(780, 20, 120, 20);

        jLabel44.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel44.setText("Ngày diễn ra");
        jPanel2.add(jLabel44);
        jLabel44.setBounds(640, 110, 140, 20);

        maJL25.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL25.setText("31");
        jPanel2.add(maJL25);
        maJL25.setBounds(830, 110, 50, 20);

        jLabel45.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel45.setText("Danh sách món ăn");
        jPanel2.add(jLabel45);
        jLabel45.setBounds(20, 260, 210, 30);

        jLabel46.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel46.setText("Trạng thái");
        jPanel2.add(jLabel46);
        jLabel46.setBounds(640, 210, 140, 20);

        maJL26.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL26.setText("makh");
        jPanel2.add(maJL26);
        maJL26.setBounds(780, 210, 120, 20);

        maJL27.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL27.setText("Ngày: ");
        jPanel2.add(maJL27);
        maJL27.setBounds(780, 110, 50, 20);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jTable11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane11.setViewportView(jTable11);

        jPanel3.add(jScrollPane11);
        jScrollPane11.setBounds(640, 300, 630, 310);

        jLabel47.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel47.setText("Tên khách hàng");
        jPanel3.add(jLabel47);
        jLabel47.setBounds(20, 80, 140, 20);

        jLabel48.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel48.setText("Căn cước công dân ");
        jPanel3.add(jLabel48);
        jLabel48.setBounds(20, 110, 140, 20);

        jLabel49.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel49.setText("Mã khách hàng");
        jPanel3.add(jLabel49);
        jLabel49.setBounds(20, 50, 120, 18);

        maJL28.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL28.setText("makh");
        jPanel3.add(maJL28);
        maJL28.setBounds(170, 110, 120, 18);

        jLabel50.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel50.setText("Mã sảnh");
        jPanel3.add(jLabel50);
        jLabel50.setBounds(20, 190, 120, 18);

        maJL29.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL29.setText("mã nhân viên");
        jPanel3.add(maJL29);
        maJL29.setBounds(170, 220, 120, 18);

        jTable12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane12.setViewportView(jTable12);

        jPanel3.add(jScrollPane12);
        jScrollPane12.setBounds(20, 500, 570, 110);

        jButton22.setText("Thêm món");
        jPanel3.add(jButton22);
        jButton22.setBounds(450, 440, 140, 23);

        jButton23.setText("Xác nhận chỉnh sửa");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton23);
        jButton23.setBounds(1090, 640, 180, 23);

        jTable13.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane13.setViewportView(jTable13);

        jPanel3.add(jScrollPane13);
        jScrollPane13.setBounds(20, 300, 570, 110);

        jButton24.setText("Thay đổi khách hàng");
        jPanel3.add(jButton24);
        jButton24.setBounds(450, 110, 140, 23);

        jLabel51.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel51.setText("Tên sảnh");
        jPanel3.add(jLabel51);
        jLabel51.setBounds(20, 220, 140, 20);

        maJL30.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL30.setText("makh");
        jPanel3.add(maJL30);
        maJL30.setBounds(170, 50, 120, 18);

        maJL31.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL31.setText("makh");
        jPanel3.add(maJL31);
        maJL31.setBounds(170, 80, 120, 18);

        jButton25.setText("Thay đổi sảnh");
        jPanel3.add(jButton25);
        jButton25.setBounds(450, 210, 140, 23);

        jButton26.setText("Xóa món");
        jPanel3.add(jButton26);
        jButton26.setBounds(250, 440, 140, 23);

        jButton27.setText("Xóa món");
        jPanel3.add(jButton27);
        jButton27.setBounds(250, 640, 140, 23);

        jButton28.setText("Thêm món");
        jPanel3.add(jButton28);
        jButton28.setBounds(450, 640, 140, 23);

        jLabel52.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel52.setText("Danh sách dịch vụ");
        jPanel3.add(jLabel52);
        jLabel52.setBounds(20, 460, 210, 30);

        jLabel53.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel53.setText("Món ăn");
        jPanel3.add(jLabel53);
        jLabel53.setBounds(20, 10, 120, 30);

        jLabel54.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel54.setText("Sảnh");
        jPanel3.add(jLabel54);
        jLabel54.setBounds(20, 150, 120, 30);

        jLabel55.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel55.setText("Danh sách ");
        jPanel3.add(jLabel55);
        jLabel55.setBounds(640, 260, 260, 30);

        maJL32.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL32.setText("mã nhân viên");
        jPanel3.add(maJL32);
        maJL32.setBounds(170, 190, 120, 18);

        jLabel56.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel56.setText("Số bàn");
        jPanel3.add(jLabel56);
        jLabel56.setBounds(640, 20, 120, 20);

        maJL33.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL33.setText("makh");
        jPanel3.add(maJL33);
        maJL33.setBounds(780, 20, 120, 20);

        jLabel57.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel57.setText("Ngày diễn ra");
        jPanel3.add(jLabel57);
        jLabel57.setBounds(640, 110, 140, 20);

        maJL34.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL34.setText("31");
        jPanel3.add(maJL34);
        maJL34.setBounds(830, 110, 50, 20);

        jLabel58.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel58.setText("Danh sách món ăn");
        jPanel3.add(jLabel58);
        jLabel58.setBounds(20, 260, 210, 30);

        jLabel59.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel59.setText("Trạng thái");
        jPanel3.add(jLabel59);
        jLabel59.setBounds(640, 210, 140, 20);

        maJL35.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL35.setText("makh");
        jPanel3.add(maJL35);
        maJL35.setBounds(780, 210, 120, 20);

        maJL36.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        maJL36.setText("Ngày: ");
        jPanel3.add(maJL36);
        maJL36.setBounds(780, 110, 50, 20);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 0, 0);

        add(jPanel2);
        jPanel2.setBounds(-1, -1, 0, 0);

        jButton29.setBackground(new java.awt.Color(51, 0, 0));
        jButton29.setForeground(new java.awt.Color(255, 255, 255));
        jButton29.setText("Quay lại");
        add(jButton29);
        jButton29.setBounds(1190, 10, 81, 23);

        jLabel61.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel61.setText("Thành tiền:");
        add(jLabel61);
        jLabel61.setBounds(1030, 530, 80, 20);

        bang.setModel(new javax.swing.table.DefaultTableModel(
            new String [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(bang);

        add(jScrollPane1);
        jScrollPane1.setBounds(570, 190, 680, 310);

        khachHangB.setBackground(new java.awt.Color(0, 51, 51));
        khachHangB.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        khachHangB.setForeground(new java.awt.Color(255, 255, 255));
        khachHangB.setText("Khách hàng");
        khachHangB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        khachHangB.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        khachHangB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khachHangBActionPerformed(evt);
            }
        });
        add(khachHangB);
        khachHangB.setBounds(20, 10, 150, 30);

        sanhB.setBackground(new java.awt.Color(0, 51, 51));
        sanhB.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        sanhB.setForeground(new java.awt.Color(255, 255, 255));
        sanhB.setText("Sảnh");
        sanhB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sanhB.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        sanhB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanhBActionPerformed(evt);
            }
        });
        add(sanhB);
        sanhB.setBounds(20, 150, 150, 30);

        monAnB.setBackground(new java.awt.Color(0, 51, 51));
        monAnB.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        monAnB.setForeground(new java.awt.Color(255, 255, 255));
        monAnB.setText("Món ăn");
        monAnB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        monAnB.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        monAnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monAnBActionPerformed(evt);
            }
        });
        add(monAnB);
        monAnB.setBounds(20, 260, 150, 30);

        xoaDV.setBackground(new java.awt.Color(0, 51, 51));
        xoaDV.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        xoaDV.setForeground(new java.awt.Color(255, 255, 255));
        xoaDV.setText("xóa dịch vụ");
        xoaDV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        xoaDV.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        xoaDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaDVActionPerformed(evt);
            }
        });
        
        xoaDV.setBounds(450, 640, 100, 20);
        add(ngaydienraTF);
        ngaydienraTF.setBounds(730, 60, 130, 20);
        add(sobanTF);
        sobanTF.setBounds(730, 20, 130, 22);

        jLabel19.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel19.setText("Ngày diễn ra");
        add(jLabel19);
        jLabel19.setBounds(570, 60, 300, 20);
        jLabel18.setText("Định dạng: Năm-Tháng-Ngày    ( ví dụ : 2023-01-01)");
        thanhtienHD = new javax.swing.JTextField();

        thanhtienHD.setText("");

        add(thanhtienHD);
        thanhtienHD.setBounds(1110, 530, 90, 20);
    }// </editor-fold>                        

    public void dichVuBActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    public void xoaMAActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    public void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    public void themHDActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    public void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    public void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    public void khachHangBActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    public void sanhBActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    public void monAnBActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    public void xoaDVActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     


    // Variables declaration - do not modify                     
    public javax.swing.JTable bang;
    public javax.swing.JTable bangDV;
    public javax.swing.JTable bangMA;
    public javax.swing.JLabel cccd;
    public javax.swing.JButton dichVuB;
    public javax.swing.JButton jButton10;
    public javax.swing.JButton jButton11;
    public javax.swing.JButton jButton12;
    public javax.swing.JButton jButton13;
    public javax.swing.JButton jButton14;
    public javax.swing.JButton jButton15;
    public javax.swing.JButton jButton16;
    public javax.swing.JButton jButton17;
    public javax.swing.JButton jButton18;
    public javax.swing.JButton jButton19;
    public javax.swing.JButton jButton20;
    public javax.swing.JButton jButton21;
    public javax.swing.JButton jButton22;
    public javax.swing.JButton jButton23;
    public javax.swing.JButton jButton24;
    public javax.swing.JButton jButton25;
    public javax.swing.JButton jButton26;
    public javax.swing.JButton jButton27;
    public javax.swing.JButton jButton28;
    public javax.swing.JButton jButton29;
    public javax.swing.JButton jButton8;
    public javax.swing.JButton jButton9;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel26;
    public javax.swing.JLabel jLabel27;
    public javax.swing.JLabel jLabel28;
    public javax.swing.JLabel jLabel29;
    public javax.swing.JLabel jLabel30;
    public javax.swing.JLabel jLabel31;
    public javax.swing.JLabel jLabel32;
    public javax.swing.JLabel jLabel33;
    public javax.swing.JLabel jLabel34;
    public javax.swing.JLabel jLabel35;
    public javax.swing.JLabel jLabel36;
    public javax.swing.JLabel jLabel37;
    public javax.swing.JLabel jLabel38;
    public javax.swing.JLabel jLabel39;
    public javax.swing.JLabel jLabel40;
    public javax.swing.JLabel jLabel41;
    public javax.swing.JLabel jLabel42;
    public javax.swing.JLabel jLabel43;
    public javax.swing.JLabel jLabel44;
    public javax.swing.JLabel jLabel45;
    public javax.swing.JLabel jLabel46;
    public javax.swing.JLabel jLabel47;
    public javax.swing.JLabel jLabel48;
    public javax.swing.JLabel jLabel49;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel50;
    public javax.swing.JLabel jLabel51;
    public javax.swing.JLabel jLabel52;
    public javax.swing.JLabel jLabel53;
    public javax.swing.JLabel jLabel54;
    public javax.swing.JLabel jLabel55;
    public javax.swing.JLabel jLabel56;
    public javax.swing.JLabel jLabel57;
    public javax.swing.JLabel jLabel58;
    public javax.swing.JLabel jLabel59;
    public javax.swing.JLabel jLabel60;
    public javax.swing.JLabel jLabel61;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane10;
    public javax.swing.JScrollPane jScrollPane11;
    public javax.swing.JScrollPane jScrollPane12;
    public javax.swing.JScrollPane jScrollPane13;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JScrollPane jScrollPane7;
    public javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JTable jTable10;
    public javax.swing.JTable jTable11;
    public javax.swing.JTable jTable12;
    public javax.swing.JTable jTable13;
    public javax.swing.JTable jTable5;
    public javax.swing.JTable jTable6;
    public javax.swing.JTable jTable7;
    public javax.swing.JTable jTable8;
    public javax.swing.JTable jTable9;
    public javax.swing.JButton khachHangB;
    public javax.swing.JLabel maJL10;
    public javax.swing.JLabel maJL11;
    public javax.swing.JLabel maJL12;
    public javax.swing.JLabel maJL13;
    public javax.swing.JLabel maJL14;
    public javax.swing.JLabel maJL15;
    public javax.swing.JLabel maJL16;
    public javax.swing.JLabel maJL17;
    public javax.swing.JLabel maJL18;
    public javax.swing.JLabel maJL19;
    public javax.swing.JLabel maJL20;
    public javax.swing.JLabel maJL21;
    public javax.swing.JLabel maJL22;
    public javax.swing.JLabel maJL23;
    public javax.swing.JLabel maJL24;
    public javax.swing.JLabel maJL25;
    public javax.swing.JLabel maJL26;
    public javax.swing.JLabel maJL27;
    public javax.swing.JLabel maJL28;
    public javax.swing.JLabel maJL29;
    public javax.swing.JLabel maJL30;
    public javax.swing.JLabel maJL31;
    public javax.swing.JLabel maJL32;
    public javax.swing.JLabel maJL33;
    public javax.swing.JLabel maJL34;
    public javax.swing.JLabel maJL35;
    public javax.swing.JLabel maJL36;
    public javax.swing.JLabel maKH;
    public javax.swing.JLabel maS;
    public javax.swing.JButton monAnB;
    public javax.swing.JTextField ngaydienraTF;
    public javax.swing.JButton sanhB;
    public javax.swing.JTextField sobanTF;
    public javax.swing.JLabel tenKH;
    public javax.swing.JLabel tenS;
    public javax.swing.JLabel thanhTienL;
    public javax.swing.JButton themHD;
    public javax.swing.JButton xoaDV;
    public javax.swing.JButton xoaMA;
    // End of variables declaration                   
	
}
